defaultAdmissionRule:
  evaluationMode: REQUIRE_ATTESTATION
  enforcementMode: ENFORCED_BLOCK_AND_AUDIT_LOG
  requireAttestationsBy:
  - projects/${PROJECT_ID}/attestors/springboard-hello-world-attestor
globalPolicyEvaluationMode: ENABLE
name: projects/${PROJECT_ID}/policy
